### PR TITLE
Create capture prescription view

### PR DESCRIPTION
**Pull request by PranayjitSingh**

### CODE REVIEW

**Comment by PranayjitSingh** [comment]
1. change to add page
2. remove garbage button

**Comment by kpirabaharan** [comment]
Yo Pranayjit, currently the medication form screen shows "Update Medication" when the optional medication prop is passed on instantiation, and "Add Medication" when a medication isnt passed.

I think the best way to fix it to show "Add Medication" on camera add method would be to instead pass a prop "isEditing" || "!isEditing" to show "Update Medication" or "Add Medication" while make it work for add Custom Medication.

**Review by Devanand-Sharma — APPROVED** [review]

**Comment by kpirabaharan** [comment]
Did you check if this works on iOS? On an actual iPhone?

**Review by kpirabaharan — DISMISSED** [review]

**Comment by kpirabaharan** [comment]
Screenshot 2024-09-15 at 23 32 29
I think you need to add this.

**Comment by PranayjitSingh** [comment]
> Did you check if this works on iOS? On an actual iPhone?

Yes, this was test on real iphone and the camera works

**Comment by PranayjitSingh** [comment]
> Screenshot 2024-09-15 at 23 32 29 I think you need to add this.

added

**Review by kpirabaharan — DISMISSED** [review]

**Review by Devanand-Sharma — APPROVED** [review]

**Review by kpirabaharan — APPROVED** [review]

**Pull request merged**
